#!/bin/bash

if [ ${1} ]
then 
		array=("$@")
		sum=$#

		for ((i=sum - 1; i >= 0; i--))
		do
				echo -n "${array[$i]}"
				if (("$i" > 0))
				then 
						echo -n " "
				fi
		done
		echo
else
		echo "No parametrs"
fi

